package com.bookstore.entity;
// Generated Dec 20, 2020, 1:28:56 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * CartItems generated by hbm2java
 */
@Entity
@Table(name = "cart_items", catalog = "bookstoredb")
@NamedQueries({
	@NamedQuery(name = "CartItem.findAll", query = "SELECT ci FROM CartItems ci ORDER BY ci.id DESC"),
	@NamedQuery(name = "CartItem.countBooks", query = "SELECT COUNT(quantity) FROM CartItems ci"),
	@NamedQuery(name = "CartItem.checkBook", query = "SELECT ci FROM CartItems ci WHERE ci.book.bookId = :bookId AND ci.customer.customerId = :customerId"),
	@NamedQuery(name = "CartItem.findByCustomer", query = "SELECT ci FROM CartItems ci WHERE ci.customer.customerId = :customerId ORDER BY ci.id DESC")
})
public class CartItems implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private Book book;
	private Customer customer;
	private Integer quantity;

	public CartItems() {
	}

	public CartItems(int id) {
		this.id = id;
	}

	public CartItems(int id, Book book, Customer customer, Integer quantity) {
		this.id = id;
		this.book = book;
		this.customer = customer;
		this.quantity = quantity;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "book_id")
	public Book getBook() {
		return this.book;
	}

	public void setBook(Book book) {
		this.book = book;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "customer_id")
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Column(name = "quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}
	
	@Transient
	public float getSubtotal() {
		return this.book.getPrice() * quantity;
	}

}
